name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Lean toolchain
      run: |
        curl -sSfL https://github.com/leanprover/elan/releases/latest/download/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
        ./elan-init -y --default-toolchain none
        export PATH="$HOME/.elan/bin:$PATH"
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
        
    - name: Build
      run: |
        export PATH="$HOME/.elan/bin:$PATH"
        timeout 3m lake build
        
    - name: Verify zero axioms and sorries
      run: |
        echo "✅ Checking for axioms and sorries..."
        
        # Look for actual axiom/sorry declarations only
        FOUND=$(grep -rE "^[[:space:]]*axiom[[:space:]]|^[[:space:]]*sorry[[:space:]]*$" *.lean || echo "")
        
        if [ -n "$FOUND" ]; then
          echo "❌ Found axioms or sorries:"
          echo "$FOUND"
          exit 1
        else
          echo "✅ Zero axioms and zero sorries confirmed!"
        fi 