name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install elan
      run: |
        set -o pipefail
        curl -sSfL https://github.com/leanprover/elan/releases/latest/download/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
        ./elan-init -y --default-toolchain none
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
    
    - name: Get cache
      run: lake exe cache get || true
    
    - name: Build project
      run: lake build
    
    - name: Verify zero axioms and sorries
      run: |
        echo "Checking for axioms and sorries..."
        if grep -n "axiom\|sorry" *.lean | grep -v "//\|--" | grep -v "Zero-axiom\|mathlib-free"; then
          echo "❌ Found axioms or sorries!"
          exit 1
        else
          echo "✅ Zero axioms and zero sorries confirmed!"
        fi 