name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Lean
      run: |
        curl -sSfL https://github.com/leanprover/elan/releases/latest/download/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
        ./elan-init -y --default-toolchain none
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
    
    - name: Build project
      run: |
        export PATH="$HOME/.elan/bin:$PATH"
        lake build
    
    - name: Verify zero axioms and sorries
      run: |
        echo "✅ Verifying zero axioms and sorries..."
        
        # Check for actual axiom/sorry declarations (not just mentions in text)
        if grep -rE "^[[:space:]]*axiom[[:space:]]|^[[:space:]]*sorry[[:space:]]*$|^[[:space:]]*sorry[[:space:]]*--" *.lean; then
          echo "❌ Found axioms or sorries in code!"
          exit 1
        else
          echo "✅ Zero axioms and zero sorries confirmed!"
        fi 