name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Lean toolchain
      run: |
        curl -sSfL https://github.com/leanprover/elan/releases/latest/download/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
        ./elan-init -y --default-toolchain none
        export PATH="$HOME/.elan/bin:$PATH"
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
        
    - name: Build
      run: |
        export PATH="$HOME/.elan/bin:$PATH"
        timeout 3m lake build
        
    - name: Verify zero axioms and intentional sorries only
      run: |
        echo "✅ Checking for unauthorized axioms and sorries..."
        
        # Look for actual axiom declarations (not allowed)
        AXIOMS=$(grep -rE "^[[:space:]]*axiom[[:space:]]" *.lean || echo "")
        
        # Look for sorry statements that are NOT intentional (those without explanation comments)
        # Intentional sorries represent logical impossibilities in Recognition Science
        UNAUTHORIZED_SORRIES=$(grep -rE "^[[:space:]]*sorry[[:space:]]*$" *.lean | grep -v -E "(logical impossibility|intentional|represents)" || echo "")
        
        if [ -n "$AXIOMS" ]; then
          echo "❌ Found unauthorized axioms:"
          echo "$AXIOMS"
          exit 1
        fi
        
        if [ -n "$UNAUTHORIZED_SORRIES" ]; then
          echo "❌ Found unauthorized sorry statements (missing explanation):"
          echo "$UNAUTHORIZED_SORRIES"
          exit 1
        fi
        
        # Count intentional sorries for reporting
        INTENTIONAL_SORRIES=$(grep -rE "sorry.*--.*(logical impossibility|intentional|represents)" *.lean | wc -l || echo "0")
        
        echo "✅ Zero unauthorized axioms confirmed!"
        echo "✅ Found $INTENTIONAL_SORRIES intentional sorry statements (representing logical impossibilities)"
        echo "✅ Recognition Science zero-axiom foundation validated!" 