name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install elan
      run: |
        set -o pipefail
        curl -sSfL https://github.com/leanprover/elan/releases/latest/download/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
        ./elan-init -y --default-toolchain none
        export PATH="$HOME/.elan/bin:$PATH"
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
    
    - name: Verify elan installation
      run: |
        export PATH="$HOME/.elan/bin:$PATH"
        which elan
        which lean
        which lake
        lean --version
    
    - name: Build project
      run: |
        export PATH="$HOME/.elan/bin:$PATH"
        lake build
    
    - name: Verify zero axioms and sorries
      run: |
        echo "Checking for axioms and sorries in Lean files..."
        echo "Files to check:"
        ls -la *.lean
        
        # Check for axioms and sorries, excluding comments and documentation
        AXIOM_COUNT=$(grep -r "^[[:space:]]*axiom\|^[[:space:]]*sorry[[:space:]]*$\|^[[:space:]]*sorry[[:space:]]*--" *.lean | grep -v "//" | wc -l || echo "0")
        
        echo "Axiom/sorry count: $AXIOM_COUNT"
        
        if [ "$AXIOM_COUNT" -eq "0" ]; then
          echo "✅ Zero axioms and zero sorries confirmed!"
        else
          echo "❌ Found axioms or sorries:"
          grep -r "^[[:space:]]*axiom\|^[[:space:]]*sorry[[:space:]]*$\|^[[:space:]]*sorry[[:space:]]*--" *.lean | grep -v "//" || echo "None found in grep"
          exit 1
        fi 